### PR TITLE
Update emberclear URL in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by amgassert**

### CODE REVIEW

**Comment by NullVoxPopuli** [comment]
What prompted this change?

**Comment by amgassert** [comment]
> What prompted this change?

Roughly a few months ago, visiting the dev build at localhost stopped working. Now local builds are served at this weird fallback IP address. I assumed it was related to some change in our build setup rather than some change on my machine, as @GreenMobius had the same issue as well IIRC.

Are you still able to visit builds at localhost?

**Comment by amgassert** [comment]
Okay, looks like this is related to the TLS change. http**s**://localhost:4201 works; I've updated the file accordingly.

**Comment by GreenMobius** [comment]
I've also never been able to access via http, it's always needed https.

**Comment by NullVoxPopuli** [comment]
Yup, https is required :/

**Comment by NullVoxPopuli** [comment]
Also, thanks for updating this! I always forget to check this stuff

**Comment by amgassert** [comment]
> When the server boots it tells you the address ;)

For me, that's `https://0.0.0.0:4201/`. Not sure why that value is given over `https://0.0.0.0:4201/`.

**Pull request merged**
